### PR TITLE
Tab manager extension

### PR DESCRIPTION
**Pull request by kushcoder12**
As per the requirement, I have created a folder regarding Tab manager extension.

### CODE REVIEW

**Comment by Morbius00** [comment]
Is it working properly ?
Please give a screenshot of it in working condition

**Comment by kodepirate** [comment]
Give reply or your PR might not be merged  @kushcoder12

**Comment by kushcoder12** [comment]
Screenshot (5)
Screenshot (6)
some ss of the extension

**Comment by kushcoder12** [comment]
@kodepirate @Morbius00 please have a look

**Comment by kodepirate** [comment]
Yo, looks really great.
Merging it 😊

**Review by kodepirate — COMMENTED** [review]
Reviewed

**Pull request merged**
