### PR TITLE
Refreshing Quotes Chrome Extention Added

### PR DESCRIPTION
**Pull request by 12rashic**
image

Kindly approve the PR and add hacktoberfest-accepted label.
Thank you

### CODE REVIEW

**Comment by kodepirate** [comment]
Have you created an issue?
First create an issues. Only then I will be able to merge it @12rashic

**Review by kodepirate — COMMENTED** [review]
ok looks good to me

**Comment by kodepirate** [comment]
Send screenshot of the extension is working @12rashic

**Comment by 12rashic** [comment]
@kodepirate Please find attched screenshots of working extention.Kindly approve the PR and add for label.
Thank you.
image

**Comment by kodepirate** [comment]
Create an issues first! @12rashic

**Comment by 12rashic** [comment]
Issue Created #53

**Comment by 12rashic** [comment]
> Have you created an issue? First create an issues. Only then I will be able to merge it @12rashic

yes done

**Pull request merged**
