### PR TITLE
created a color picker chrome extension

### PR DESCRIPTION
**Pull request by yosaami**
I've created a color picker chrome extension using html, css, javascript. Once enabled it, its icon(picker tool) can be seen on the top right corner, clicking on which will open a tool which can detect the color of the webpage element and give its hexcode.  Please let me know if it needs any change.
Screenshot (29)

### CODE REVIEW

**Comment by kodepirate** [comment]
Is it working properly? @yosaami

**Comment by yosaami** [comment]
yes its working properly

**Comment by kodepirate** [comment]
ok merging it @yosaami

**Review by kodepirate — COMMENTED** [review]
OK

**Pull request merged**
