### PR TITLE
website-toggler-extension created

### PR DESCRIPTION
**Pull request by Koustavjr**
@kodepirate @Morbius00 can u please check my pr...i have added ss in the readme.

### CODE REVIEW

**Comment by Koustavjr** [comment]
@Morbius00 can u plss check my pr.

**Comment by kodepirate** [comment]
Ok Looks fine 
But before merge I want you to give a proper name to your folder !!
@Koustavjr

**Comment by Koustavjr** [comment]
@kodepirate will this name do?

**Comment by Koustavjr** [comment]
@kodepirate @Morbius00 will this name to the folder alright??

**Comment by kodepirate** [comment]
Show screenshot of its working @Koustavjr

**Comment by Koustavjr** [comment]
@kodepirate I have given it on the readme file .

**Pull request merged**
