### PR TITLE
added phishing url detection extension

### PR DESCRIPTION
**Pull request by amitkroutthedev**
Added an extension which will able to show if that website is phish or legitimate

### CODE REVIEW

**Comment by kodepirate** [comment]
Have you created an issue?
Create an issues first only then I will be able to merge it @amitkroutthedev

**Comment by amitkroutthedev** [comment]
Yeah create an issue(#52 )

**Comment by kodepirate** [comment]
And what are you working in the #49 issue !?? @amitkroutthedev

**Comment by amitkroutthedev** [comment]
#49  is suggestion on adding the extension

**Comment by amitkroutthedev** [comment]
I have also deployed it on Microsoft Edge AddOn market

**Review by kodepirate — COMMENTED** [review]
Ok Good to me

**Pull request merged**
