### PR TITLE
Added Youtube ad blocker Extension

### PR DESCRIPTION
**Pull request by Rohit-Kavitake**

### CODE REVIEW

**Comment by kodepirate** [comment]
Share screenshot of its working @Rohit-Kavitake

**Comment by kodepirate** [comment]
Put a comment in the PR section to get assigned @Rohit-Kavitake

**Comment by Rohit-Kavitake** [comment]
adblocker2
adblocker
not auto enabled on other websites
enables on youtube website

It automatically enables on youtube website , last 2 screenshots shows the extension icon enabled on right top of address bar

**Comment by kodepirate** [comment]
Actually looks great dude @Rohit-Kavitake

**Comment by kodepirate** [comment]
Can you please make a comment in the issue section. I can't assign you @Rohit-Kavitake

**Pull request merged**
