### PR TITLE
pranking extension added

### PR DESCRIPTION
**Pull request by RidhamRj**
#69 
resolved the issue

kindly check the readme files for further details

hope this satisfies the repo 
just tag me for any further suggestions related to this

https://user-images.githubusercontent.com/86556438/196978764-a7e156df-35f0-4ced-a3f5-2f566f45b704.mp4

### CODE REVIEW

**Comment by Morbius00** [comment]
> @Morbius00 kindly review

Add screen shot of your extension in working condition

**Comment by RidhamRj** [comment]
Alright

**Comment by RidhamRj** [comment]
@Morbius00 done bro

**Review by kodepirate — COMMENTED** [review]
Looks great to me.. Have done a good job dude

**Pull request merged**
